baseURL = "https://aesopos.co.kr"
languageCode = "en-us"
paginate = 6
theme = "portio"
title = "이솝이야기"
[[menu.main]]
name = "Contact"
url = "#contact"
weight = 7
[[menu.main]]
name = "Blog"
url = "#blog"
weight = 6
[[menu.main]]
name = "Work"
url = "#resume"
weight = 5
[[menu.main]]
name = "Portfolio"
url = "#portfolio"
weight = 4
[[menu.main]]
name = "Service"
url = "#service"
weight = 3
[[menu.main]]
name = "About"
url = "#about"
weight = 2
[[menu.main]]
name = "Home"
url = "#home"
weight = 1
[[menu.sitemap]]
name = "Latest Article"
url = "#"
weight = 4
[[menu.sitemap]]
name = "Privacy & Policy"
url = "#"
weight = 3
[[menu.sitemap]]
name = "Frequently Ask Question"
url = "#"
weight = 2
[[menu.sitemap]]
name = "sitemap"
url = "#"
weight = 1
[params]
blogPageURL = "blog"
contactLink = "contact"
copyright = "All right reserved copyright © Aesopos Inc 2019"
footerLogo = "images/contact/widget-logo.png"
formspreeURL = "YOUR FORMSPREE URL"
googleAnalytics = "UA-156657834-1"
logo = "images/site-navigation/logo.png"
[params.address]
address = "대전 중구 계백로 1719, 센트리아오피스텔 1203호"
email = "aesoposinc@gmail.com"
openingHours = "평일 오전 9시 - 오후 6시  <br>주말,공휴일 휴무"
phone = "1600-5478"
[params.map]
APIkey = "https://maps.googleapis.com/maps/api/js?key=AIzaSyATccESqUYbZ4N7eCEaHjqifzQmwqF6nuU&libraries=places"
latitude = "36.322181"
longitude = "127.410475"
pinImage = "images/pin.png"
[[params.social]]
icon = "fa-facebook-official"
url = "https://www.facebook.com/aesoposinc"
weight = 1
[[params.social]]
icon = "fa-linkedin-square"
url = "https://www.linkedin.com/"
weight = 2
[[params.social]]
icon = "fa-pinterest-square"
url = "https://www.pinterest.com/"
weight = 3
[[params.social]]
icon = "fa-twitter-square"
url = "https://twitter.com/"
weight = 4
